### ISSUE TITLE
Error E688 with the function <SNR>239_ToggleType…

### ISSUE THREAD

**Issue by bmenant** [tacahiroy/ctrlp-funky#38] opened 2014-06-18 14:57 UTC
Hello,

This error is often displayed when I open the Funky tab with CtrlP: 
```
Erreur détectée en traitant function <SNR>239_ToggleType..ctrlp#setlines..ctrlp#funky#init..ctrlp#funky#extract:
ligne 26:
E688: Plus de destinations que d'éléments dans la Liste
```

It does not occur all the time, but I cannot figure out when. For instance, I got the error with PHP, Javascript, CoffeeScript and HTML files.

N.B. I use the spf13 vim distribution.

**Comment by funny-code** [comment] 2015-01-06 14:20
local Test = {}
Test.abc = function()
    print("test")
end

**Comment by funny-code** [comment] 2015-01-06 14:23
[test lua file]:

local Test = {}
Test.abc = function()
    print("test")
end

[mini vimrc]:

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'tacahiroy/ctrlp-funky'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'tpope/vim-fugitive'
Bundle 'kien/ctrlp.vim'
call vundle#end()

let mapleader = ","

noremap <c-h> <c-w>h
noremap <c-j> <c-w>j
noremap <c-k> <c-w>k
noremap <c-l> <c-w>l

noremap H <c-w><
noremap J <c-w>+
noremap K <c-w>-
noremap L <c-w>>

noremap <C-a> :CtrlP /home/lpy/<CR>
let g:ctrlp_extensions = ['funky']
nnoremap <leader>fb :CtrlPFunky<Cr>
nnoremap <leader>fU :execute 'CtrlPFunky ' . expand('<cword>')<Cr>
nnoremap <leader>b :CtrlPBuffer<CR>

let g:EasyMotion_leader_key = 'f'
nmap s <Plug>(easymotion-s2)
map  / <Plug>(easymotion-sn)
omap / <Plug>(easymotion-tn)
map  n <Plug>(easymotion-next)
map  N <Plug>(easymotion-prev)
map <Leader>l <Plug>(easymotion-lineforward)
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)
map <Leader>h <Plug>(easymotion-linebackward)

let g:EasyMotion_startofline = 0
map <Leader> <Plug>(easymotion-prefix)

filetype plugin indent on
set nu
let g:ctrlp_funky_matchtype = 'path'
let g:ctrlp_funky_syntax_highlight = 1
set ruler
"set cursorline
syntax on
set incsearch
set showmatch
set shiftwidth=4
set tabstop=4
set nocompatible
set expandtab
set hlsearch

处理 function ctrlp#funky#funky..ctrlp#init..ctrlp#setlines..ctrlp#funky#init..ctrlp#funky#extract 时发生错误:
第   45 行:
E688: 目标比 List 项数多

**Comment by bmenant** [comment] 2015-01-13 18:41
I reinstalled my system from scratch when I got my new computer. Since that time the issue has not occured.

**Comment by fufler** [comment] 2015-04-14 16:22
It seems that I have tha same issues (E688 too). It looks like error occurs only when non-english locale is set, i.e. if I run export LC_ALL=en_US.UTF-8 before launching vim this error never appears.

**Comment by fufler** [comment] 2015-04-14 17:06
OK, seems I've found a reason. When russian locale is set [this](https://github.com/tacahiroy/ctrlp-funky/blob/master/autoload/ctrlp/funky.vim#L281) condition is never met, so we have problems with further regexp matches. Moreover, with russian locale set there is no error code in Vim error message (it says «Pattern not found» in russian instead of «E486: Pattern not found»), so there's no way to create regexp suitable for all locales. It seems there is a safety [check](https://github.com/tacahiroy/ctrlp-funky/blob/master/autoload/ctrlp/funky.vim#L283)  for such cases but it's probably done wrong (please, explain, if it's not, since I'm not familar with vimscript syntax). I'd like to suggest to apply this patch to plugin's code:

```diff
diff --git a/autoload/ctrlp/funky.vim b/autoload/ctrlp/funky.vim
index ee5b70f..4cbb87c 100644
--- a/autoload/ctrlp/funky.vim
+++ b/autoload/ctrlp/funky.vim
@@ -280,7 +280,7 @@ function! ctrlp#funky#extract(bufnr, patterns)
 
       if ilist !~# '\n\(E486: \)\?Pattern not found:'
         for l in split(ilist, '\n')
-          if l =~# '^ \t#:\d\+:\d\+$'
+          if l !~# '#:\d\+:\d\+$'
             continue
           endif
           let [left, right] = split(l, '\ze \t#:\d\+:\d\+')
```

**Comment by bmenant** [comment] 2015-04-15 00:33
It makes sense, since my last OS was set up with a non-english locale.

**Comment by tacahiroy** [comment] 2015-04-15 14:46
@fufler Nice one!!
Although I still don't reproduce on my laptop, OS X 10.10.3, the condition `if ilist !~# '\n\(E486: \)\?Pattern not found:'` is bad. In that case, indeed, the condition becomes true in any non-English environments if no patterns found.
So I think like this change fixes the problem:
```patch
diff --git i/autoload/ctrlp/funky.vim w/autoload/ctrlp/funky.vim                                                                   │
index ee5b70f..b61b571 100644                                                                                                      │
--- i/autoload/ctrlp/funky.vim                                                                                                     │
+++ w/autoload/ctrlp/funky.vim                                                                                                     │
@@ -278,11 +278,8 @@ function! ctrlp#funky#extract(bufnr, patterns)                                                                │
         execute 'silent! global/' . c.pattern . '/echo printf("%s \t#%s:%d:%d", getline(line(".") + offset), "", a:bufnr, line("."│
) + offset)'                                                                                                                       │
       redir END                                                                                                                   │
                                                                                                                                   │
-      if ilist !~# '\n\(E486: \)\?Pattern not found:'                                                                             │
+      if ilist =~# '\s\t#:\d\+:\d\+$'                                                                                             │
         for l in split(ilist, '\n')                                                                                               │
-          if l =~# '^ \t#:\d\+:\d\+$'                                                                                             │
-            continue                                                                                                              │
-          endif                                                                                                                   │
           let [left, right] = split(l, '\ze \t#:\d\+:\d\+')                                                                       │
           let formatter = c.formatter                                                                                             │
           let [pat, str, flags] = [get(formatter, 0, ''), get(formatter, 1, ''), get(formatter, 2, '')]
```

It would be pretty appreciated if you guys confirm whether this patch works.

Many Thanks!

**Comment by fufler** [comment] 2015-04-15 14:54
@tacahiroy, yep, this patch works for me.

**Comment by tacahiroy** [comment] 2015-04-15 15:00
@fufler cool - thanks for your confirmation. I'll push this changes to master in 10 mins or so.

**Comment by tacahiroy** [comment] 2015-04-15 15:21
Thanks guys! I've just pushed changes to master.
Finally closing.

**Closed by tacahiroy** 2015-04-15 15:21 UTC
Labels: bug

**Comment by Layzie** [comment] 2015-04-16 01:43
@tacahiroy @fufler Thanks!! This patch works well! I can use ctrlp-funky again.
